// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------



[System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/", ConfigurationName="IFleetService")]
public interface IFleetService {
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/RegisterClient", ReplyAction="http://tempuri.org/IFleetService/RegisterClientResponse")]
    FleetServer.FleetClientToken RegisterClient(FleetServer.FleetClientRegistration registrationModel);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/Heartbeat", ReplyAction="http://tempuri.org/IFleetService/HeartbeatResponse")]
    FleetServer.FleetHearbeatEnum Heartbeat(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier[] knownClients);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/QueryClients", ReplyAction="http://tempuri.org/IFleetService/QueryClientsResponse")]
    FleetServer.FleetClientIdentifier[] QueryClients(FleetServer.FleetClientToken token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/QueryFiles", ReplyAction="http://tempuri.org/IFleetService/QueryFilesResponse")]
    FleetServer.FleetFileIdentifier[] QueryFiles(FleetServer.FleetClientToken token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/GetFile", ReplyAction="http://tempuri.org/IFleetService/GetFileResponse")]
    FleetServer.FleetFile GetFile(FleetServer.FleetClientToken token, FleetServer.FleetFileIdentifier fileId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/SendFileSingleRecipient", ReplyAction="http://tempuri.org/IFleetService/SendFileSingleRecipientResponse")]
    bool SendFileSingleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier recipient, FleetServer.FleetFile file);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/SendFileMultipleRecipient", ReplyAction="http://tempuri.org/IFleetService/SendFileMultipleRecipientResponse")]
    bool SendFileMultipleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier[] recipients, FleetServer.FleetFile file);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/QueryMessages", ReplyAction="http://tempuri.org/IFleetService/QueryMessagesResponse")]
    FleetServer.FleetMessageIdentifier[] QueryMessages(FleetServer.FleetClientToken token);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/GetMessage", ReplyAction="http://tempuri.org/IFleetService/GetMessageResponse")]
    FleetServer.FleetMessage GetMessage(FleetServer.FleetClientToken token, FleetServer.FleetMessageIdentifier fileId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/SendMessageSingleRecipient", ReplyAction="http://tempuri.org/IFleetService/SendMessageSingleRecipientResponse")]
    bool SendMessageSingleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier recipient, FleetServer.FleetMessage msg);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFleetService/SendMessageMultipleRecipient", ReplyAction="http://tempuri.org/IFleetService/SendMessageMultipleRecipientResponse")]
    bool SendMessageMultipleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier[] recipients, FleetServer.FleetMessage msg);
}

public interface IFleetServiceChannel : IFleetService, System.ServiceModel.IClientChannel {
}

public class FleetServiceClient : System.ServiceModel.ClientBase<IFleetService>, IFleetService {
    
    public FleetServiceClient() {
    }
    
    public FleetServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName) {
    }
    
    public FleetServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public FleetServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress) {
    }
    
    public FleetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress endpoint) : 
            base(binding, endpoint) {
    }
    
    public FleetServer.FleetClientToken RegisterClient(FleetServer.FleetClientRegistration registrationModel) {
        return base.Channel.RegisterClient(registrationModel);
    }
    
    public FleetServer.FleetHearbeatEnum Heartbeat(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier[] knownClients) {
        return base.Channel.Heartbeat(token, knownClients);
    }
    
    public FleetServer.FleetClientIdentifier[] QueryClients(FleetServer.FleetClientToken token) {
        return base.Channel.QueryClients(token);
    }
    
    public FleetServer.FleetFileIdentifier[] QueryFiles(FleetServer.FleetClientToken token) {
        return base.Channel.QueryFiles(token);
    }
    
    public FleetServer.FleetFile GetFile(FleetServer.FleetClientToken token, FleetServer.FleetFileIdentifier fileId) {
        return base.Channel.GetFile(token, fileId);
    }
    
    public bool SendFileSingleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier recipient, FleetServer.FleetFile file) {
        return base.Channel.SendFileSingleRecipient(token, recipient, file);
    }
    
    public bool SendFileMultipleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier[] recipients, FleetServer.FleetFile file) {
        return base.Channel.SendFileMultipleRecipient(token, recipients, file);
    }
    
    public FleetServer.FleetMessageIdentifier[] QueryMessages(FleetServer.FleetClientToken token) {
        return base.Channel.QueryMessages(token);
    }
    
    public FleetServer.FleetMessage GetMessage(FleetServer.FleetClientToken token, FleetServer.FleetMessageIdentifier fileId) {
        return base.Channel.GetMessage(token, fileId);
    }
    
    public bool SendMessageSingleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier recipient, FleetServer.FleetMessage msg) {
        return base.Channel.SendMessageSingleRecipient(token, recipient, msg);
    }
    
    public bool SendMessageMultipleRecipient(FleetServer.FleetClientToken token, FleetServer.FleetClientIdentifier[] recipients, FleetServer.FleetMessage msg) {
        return base.Channel.SendMessageMultipleRecipient(token, recipients, msg);
    }
}
namespace tempuri.org {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterClient", Namespace="http://tempuri.org/")]
    public partial class RegisterClient : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetClientRegistration registrationModelField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetClientRegistration registrationModel {
            get {
                return this.registrationModelField;
            }
            set {
                this.registrationModelField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegisterClientResponse", Namespace="http://tempuri.org/")]
    public partial class RegisterClientResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetClientToken RegisterClientResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetClientToken RegisterClientResult {
            get {
                return this.RegisterClientResultField;
            }
            set {
                this.RegisterClientResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Heartbeat", Namespace="http://tempuri.org/")]
    public partial class Heartbeat : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetClientToken tokenField;
        
        private FleetServer.FleetClientIdentifier[] knownClientsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetClientToken token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public FleetServer.FleetClientIdentifier[] knownClients {
            get {
                return this.knownClientsField;
            }
            set {
                this.knownClientsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HeartbeatResponse", Namespace="http://tempuri.org/")]
    public partial class HeartbeatResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetHearbeatEnum HeartbeatResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetHearbeatEnum HeartbeatResult {
            get {
                return this.HeartbeatResultField;
            }
            set {
                this.HeartbeatResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryClients", Namespace="http://tempuri.org/")]
    public partial class QueryClients : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetClientToken tokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetClientToken token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryClientsResponse", Namespace="http://tempuri.org/")]
    public partial class QueryClientsResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetClientIdentifier[] QueryClientsResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetClientIdentifier[] QueryClientsResult {
            get {
                return this.QueryClientsResultField;
            }
            set {
                this.QueryClientsResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryFiles", Namespace="http://tempuri.org/")]
    public partial class QueryFiles : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetClientToken tokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetClientToken token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryFilesResponse", Namespace="http://tempuri.org/")]
    public partial class QueryFilesResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetFileIdentifier[] QueryFilesResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetFileIdentifier[] QueryFilesResult {
            get {
                return this.QueryFilesResultField;
            }
            set {
                this.QueryFilesResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFile", Namespace="http://tempuri.org/")]
    public partial class GetFile : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetClientToken tokenField;
        
        private FleetServer.FleetFileIdentifier fileIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetClientToken token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public FleetServer.FleetFileIdentifier fileId {
            get {
                return this.fileIdField;
            }
            set {
                this.fileIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetFileResponse", Namespace="http://tempuri.org/")]
    public partial class GetFileResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetFile GetFileResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetFile GetFileResult {
            get {
                return this.GetFileResultField;
            }
            set {
                this.GetFileResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendFileSingleRecipient", Namespace="http://tempuri.org/")]
    public partial class SendFileSingleRecipient : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetClientToken tokenField;
        
        private FleetServer.FleetClientIdentifier recipientField;
        
        private FleetServer.FleetFile fileField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetClientToken token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public FleetServer.FleetClientIdentifier recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public FleetServer.FleetFile file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendFileSingleRecipientResponse", Namespace="http://tempuri.org/")]
    public partial class SendFileSingleRecipientResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SendFileSingleRecipientResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SendFileSingleRecipientResult {
            get {
                return this.SendFileSingleRecipientResultField;
            }
            set {
                this.SendFileSingleRecipientResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendFileMultipleRecipient", Namespace="http://tempuri.org/")]
    public partial class SendFileMultipleRecipient : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetClientToken tokenField;
        
        private FleetServer.FleetClientIdentifier[] recipientsField;
        
        private FleetServer.FleetFile fileField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetClientToken token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public FleetServer.FleetClientIdentifier[] recipients {
            get {
                return this.recipientsField;
            }
            set {
                this.recipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public FleetServer.FleetFile file {
            get {
                return this.fileField;
            }
            set {
                this.fileField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendFileMultipleRecipientResponse", Namespace="http://tempuri.org/")]
    public partial class SendFileMultipleRecipientResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SendFileMultipleRecipientResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SendFileMultipleRecipientResult {
            get {
                return this.SendFileMultipleRecipientResultField;
            }
            set {
                this.SendFileMultipleRecipientResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryMessages", Namespace="http://tempuri.org/")]
    public partial class QueryMessages : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetClientToken tokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetClientToken token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QueryMessagesResponse", Namespace="http://tempuri.org/")]
    public partial class QueryMessagesResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetMessageIdentifier[] QueryMessagesResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetMessageIdentifier[] QueryMessagesResult {
            get {
                return this.QueryMessagesResultField;
            }
            set {
                this.QueryMessagesResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMessage", Namespace="http://tempuri.org/")]
    public partial class GetMessage : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetClientToken tokenField;
        
        private FleetServer.FleetMessageIdentifier fileIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetClientToken token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public FleetServer.FleetMessageIdentifier fileId {
            get {
                return this.fileIdField;
            }
            set {
                this.fileIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetMessageResponse", Namespace="http://tempuri.org/")]
    public partial class GetMessageResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetMessage GetMessageResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetMessage GetMessageResult {
            get {
                return this.GetMessageResultField;
            }
            set {
                this.GetMessageResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMessageSingleRecipient", Namespace="http://tempuri.org/")]
    public partial class SendMessageSingleRecipient : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetClientToken tokenField;
        
        private FleetServer.FleetClientIdentifier recipientField;
        
        private FleetServer.FleetMessage msgField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetClientToken token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public FleetServer.FleetClientIdentifier recipient {
            get {
                return this.recipientField;
            }
            set {
                this.recipientField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public FleetServer.FleetMessage msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMessageSingleRecipientResponse", Namespace="http://tempuri.org/")]
    public partial class SendMessageSingleRecipientResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SendMessageSingleRecipientResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SendMessageSingleRecipientResult {
            get {
                return this.SendMessageSingleRecipientResultField;
            }
            set {
                this.SendMessageSingleRecipientResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMessageMultipleRecipient", Namespace="http://tempuri.org/")]
    public partial class SendMessageMultipleRecipient : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private FleetServer.FleetClientToken tokenField;
        
        private FleetServer.FleetClientIdentifier[] recipientsField;
        
        private FleetServer.FleetMessage msgField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FleetServer.FleetClientToken token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public FleetServer.FleetClientIdentifier[] recipients {
            get {
                return this.recipientsField;
            }
            set {
                this.recipientsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public FleetServer.FleetMessage msg {
            get {
                return this.msgField;
            }
            set {
                this.msgField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMessageMultipleRecipientResponse", Namespace="http://tempuri.org/")]
    public partial class SendMessageMultipleRecipientResponse : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool SendMessageMultipleRecipientResultField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SendMessageMultipleRecipientResult {
            get {
                return this.SendMessageMultipleRecipientResultField;
            }
            set {
                this.SendMessageMultipleRecipientResultField = value;
            }
        }
    }
}
namespace FleetServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetClientRegistration", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetClientRegistration : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FriendlyNameField;
        
        private string IpAddressField;
        
        private string MacAddressField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FriendlyName {
            get {
                return this.FriendlyNameField;
            }
            set {
                this.FriendlyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IpAddress {
            get {
                return this.IpAddressField;
            }
            set {
                this.IpAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MacAddress {
            get {
                return this.MacAddressField;
            }
            set {
                this.MacAddressField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetClientToken", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetClientToken : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdentifierField;
        
        private string TokenField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                this.IdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                this.TokenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetClientIdentifier", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetClientIdentifier : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IdentifierField;
        
        private string WorkstationNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                this.IdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkstationName {
            get {
                return this.WorkstationNameField;
            }
            set {
                this.WorkstationNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetHearbeatEnum", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public enum FleetHearbeatEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoUpdates = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ClientUpdate = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ControlUpdate = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ManageUpdate = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FileAvailable = 16,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetFileIdentifier", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetFileIdentifier : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string FileNameField;
        
        private int FileSizeField;
        
        private string IdentifierField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FileSize {
            get {
                return this.FileSizeField;
            }
            set {
                this.FileSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                this.IdentifierField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetFile", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetFile : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private byte[] FileContentsField;
        
        private string FileNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] FileContents {
            get {
                return this.FileContentsField;
            }
            set {
                this.FileContentsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                this.FileNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetMessageIdentifier", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetMessageIdentifier : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ApplicationIdField;
        
        private int IdentifierField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                this.ApplicationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                this.IdentifierField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FleetMessage", Namespace="http://schemas.datacontract.org/2004/07/FleetServer")]
    public partial class FleetMessage : object, System.Runtime.Serialization.IExtensibleDataObject {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ApplicationIdField;
        
        private int IdentifierField;
        
        private string MessageField;
        
        private System.DateTime SentField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ApplicationId {
            get {
                return this.ApplicationIdField;
            }
            set {
                this.ApplicationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Identifier {
            get {
                return this.IdentifierField;
            }
            set {
                this.IdentifierField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Sent {
            get {
                return this.SentField;
            }
            set {
                this.SentField = value;
            }
        }
    }
}
